<?php

namespace Hexaa\StorageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EntitlementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntitlementRepository extends EntityRepository
{
    public function findAllByOrganization(Organization $o, $limit = null, $offset = 0)
    {
        $es = $this->getEntityManager()->createQueryBuilder()
                ->select('e')
                ->from('HexaaStorageBundle:Entitlement', 'e')
                ->from('HexaaStorageBundle:OrganizationEntitlementPack', 'oep')
                ->innerJoin('oep.entitlementPack', 'ep')
                ->where('oep.organization = :o')
                ->andWhere('e MEMBER OF ep.entitlements')
                ->setParameters(array('o' => $o))
                ->getQuery()
                ->getResult()
        ;
        return $es;
    }
    
}