<?php

/**
 * Copyright 2014-2018 MTA SZTAKI, ugyeletes@sztaki.hu
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace Hexaa\StorageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EntitlementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntitlementRepository extends EntityRepository
{

    public function findAllByOrganization(Organization $o, $limit = null, $offset = 0)
    {
        $es = $this->getEntityManager()->createQueryBuilder()
          ->select('entitlement')
          ->from('HexaaStorageBundle:Entitlement', 'entitlement')
          ->leftJoin('entitlement.links', 'link1')
          ->leftJoin('entitlement.entitlementPacks', 'eps')
          ->leftJoin('eps.links', 'link2')
          ->where(
            "(link1.organization = :o AND link1.status = 'accepted') "
            ."OR (link2.organization = :o AND link2.status = 'accepted')"
          )
          ->setFirstResult($offset)
          ->setMaxResults($limit)
          ->setParameter(':o', $o)
          ->orderBy('entitlement.name', 'ASC')
          ->getQuery()
          ->getResult();

        return $es;
    }

    public function findAllByPrincipal(Principal $p, $limit = null, $offset = 0)
    {
        return $this->getEntityManager()->createQueryBuilder()
          ->select('e')
          ->from('HexaaStorageBundle:Entitlement', 'e')
          ->from('HexaaStorageBundle:RolePrincipal', 'rp')
          ->innerJoin('rp.role', 'r')
          ->where('e MEMBER OF r.entitlements ')
          ->andWhere('rp.principal = :p')
          ->setFirstResult($offset)
          ->setMaxResults($limit)
          ->setParameters(array("p" => $p))
          ->orderBy('e.name', 'ASC')
          ->getQuery()
          ->getResult();
    }

    public function findAllByPrincipalAndService(Principal $p, Service $s, $limit = null, $offset = 0)
    {
        return $this->getEntityManager()->createQueryBuilder()
          ->select('e')
          ->from('HexaaStorageBundle:Entitlement', 'e')
          ->innerJoin('e.roles', 'r')
          ->innerJoin('r.principals', 'rp')
          ->where('rp.principal = :p')
          ->andWhere('e.service = :s')
          ->andWhere('rp.principal = :p')
          ->andWhere('e.service = :s')
          ->setFirstResult($offset)
          ->setMaxResults($limit)
          ->setParameters(array("p" => $p, "s" => $s))
          ->orderBy('e.name', 'ASC')
          ->getQuery()
          ->getResult();
    }

    public function findAllByPrincipalAndServiceStrict(Principal $p, Service $s, $limit = null, $offset = 0)
    {
        return $this->getEntityManager()->createQueryBuilder()
          ->select('e')
          ->from('HexaaStorageBundle:Entitlement', 'e')
          ->innerJoin('e.roles', 'r')
          ->innerJoin('r.principals', 'rp')
          ->where('rp.principal = :p')
          ->andWhere('e.service = :s')
          ->andWhere('(r.startDate <= :now or r.startDate is null)')
          ->andWhere('(r.endDate >= :now or r.endDate is null)')
          ->setFirstResult($offset)
          ->setMaxResults($limit)
          ->setParameters(array("p" => $p, "s" => $s, "now" => new \DateTime('now')))
          ->orderBy('e.name', 'ASC')
          ->getQuery()
          ->getResult();
    }

}
