<?php

/**
 * Copyright 2014-2018 MTA SZTAKI, ugyeletes@sztaki.hu
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace Hexaa\StorageBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * EntitlementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntitlementPackRepository extends EntityRepository
{

    public function findOneByToken($token)
    {
        $ep = $this->getEntityManager()->createQueryBuilder()
          ->select('ep')
          ->from('HexaaStorageBundle:EntitlementPack', 'ep')
          ->leftJoin("ep.tokens", "tokens")
          ->where('tokens.token = :t')
          ->setParameters(array(":t" => $token))
          ->getQuery()
          ->getOneOrNullResult();

        return $ep;
    }

    public function findAllByRelatedPrincipal(Principal $p, $limit = null, $offset = 0)
    {
        $eps = $this->getEntityManager()->createQueryBuilder()
          ->select('ep')
          ->from('HexaaStorageBundle:EntitlementPack', 'ep')
          ->innerJoin('HexaaStorageBundle:Link', 'link')
          ->innerJoin('link.organization', 'o')
          ->innerJoin("ep.service", "s")
          ->where(':p MEMBER OF o.principals ')
          ->andWhere("link.status='accepted'")
          ->andWhere("s.isEnabled=true")
          ->setFirstResult($offset)
          ->setMaxResults($limit)
          ->orderBy("ep.name", "ASC")
          ->setParameters(array(":p" => $p))
          ->getQuery()
          ->getResult();

        return $eps;
    }

}
