<?php

namespace Hexaa\StorageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrganizationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizationRepository extends EntityRepository
{

    public function findAllByMember(Principal $p, $limit = null, $offset = 0)
    {
        return $this->getEntityManager()->createQueryBuilder()
            ->select('o')
            ->from('HexaaStorageBundle:Organization', 'o')
            ->innerJoin('o.principals', 'm')
            ->where(':p MEMBER OF o.principals')
            ->setFirstResult($offset)
            ->setMaxResults($limit)
            ->orderBy("o.name", "ASC")
            ->setParameters(array(":p" => $p))
            ->getQuery()
            ->getResult();
    }

    public function getIdsByEntitlementPack(EntitlementPack $ep)
    {
        $ids = $this->getEntityManager()->createQueryBuilder()
            ->select('o.id')
            ->from("HexaaStorageBundle:Organization", "o")
            ->innerJoin("HexaaStorageBundle:OrganizationEntitlementPack", "oep", "WITH", "o = oep.organization")
            ->where("oep.entitlementPack = :ep")
            ->setParameter(":ep", $ep)
            ->getQuery()
            ->getScalarResult();
        $oIds = array();
        foreach ($ids as $id) {
            $oIds[] = $id['id'];
        }

        return $oIds;
    }
}
