<?php

namespace Hexaa\StorageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PrincipalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrincipalRepository extends EntityRepository {

    public function findOneByPersonalToken($pt) {
        $p = $this->getEntityManager()->createQueryBuilder()
            ->select('p')
            ->from('HexaaStorageBundle:Principal', 'p')
            ->innerJoin('p.token', 'pt')
            ->where('pt.token = :pt')
            ->setParameters(array('pt' => $pt))
            ->getQuery()
            ->getOneOrNullResult();

        return $p;
    }
}
