<?php

namespace Hexaa\StorageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends EntityRepository {

    public function findAllByRelatedPrincipal(Principal $p, $limit = null, $offset = 0) {
        $ss = $this->getEntityManager()->createQueryBuilder()
            ->select('s')
            ->from('HexaaStorageBundle:Service', 's')
            ->innerJoin('HexaaStorageBundle:EntitlementPack', 'ep', 'WITH', 'ep.service = s')
            ->innerJoin('HexaaStorageBundle:OrganizationEntitlementPack', 'oep', 'WITH', 'oep.entitlementPack = ep')
            ->leftJoin('oep.organization', 'o')
            ->where(':p MEMBER OF o.principals ')
            ->andWhere("oep.status='accepted'")
            ->andWhere("s.isEnabled=true")
            ->setFirstResult($offset)
            ->setMaxResults($limit)
            ->orderBy("s.name", "ASC")
            ->setParameters(array(":p" => $p))
            ->getQuery()
            ->getResult();

        return $ss;
    }

}
