imports:
    - { resource: parameters.yml }
    - { resource: hexaa_entityids.yml }
    - { resource: hexaa_admins.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:
        fallback: %locale%
        enabled: true
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: true
    validation:
        enable_annotations: true
        api: auto
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_proxies: 127.0.0.1
    
    session:         
        name:        "symfony"
        cookie_path: "/"
        save_path:   "/var/lib/php5" 
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        server_version: %database_version%
        charset:  UTF8
        mapping_types:
            enum: string
            set: string

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    port:      %mailer_port%
    username:  %mailer_user%
    password:  %mailer_password%
    #spool:     { type: memory }

sensio_framework_extra:
    view: { annotations: true }

fos_rest:
    disable_csrf_role: ROLE_API
    
    param_fetcher_listener: true
    view:
        view_response_listener: 'force'
        formats:
            xml:  true
            json: true
        templating_formats:
            html: true
        serialize_null: true
    format_listener:
        rules:
            - { path: ^/api, priorities: [ json, xml, html ], fallback_format: json, prefer_extension: true }
            - { path: ^/, priorities: [ html, css ], fallback_format: html, prefer_extension: true }
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
            
    allowed_methods_listener: true
    access_denied_listener:
        json: true
    body_listener: true
    serializer:
        serialize_null: true

nelmio_api_doc: 
    name: HEXAA REST API
    motd: 
        template: HexaaApiBundle::Default/motd.html.twig
    request_listener:
        enabled:              true
        parameter:            _doc
    sandbox:
        authentication:
           name: X-HEXAA-AUTH
           delivery: header
        enabled: true 
        body_format:
            formats: [ form, json ]
            default_format: json
        request_format:
            formats:
                json: application/json
                xml: application/xml
            default_format: json

nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
    paths:
        '^/api/':
            allow_origin: %hexaa_cors_origins%
            allow_headers: ['X-Hexaa-Auth', 'accept', 'content-type', 'location']
            allow_methods: ['PATCH', 'POST', 'PUT', 'GET', 'DELETE']
            expose_headers: ['location']
            max_age: 3600

bazinga_hateoas: ~

bazinga_rest_extra: ~
