imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

#jns_xhprof:
#    location_web:    http://localhost/xhprof
#    enabled:         true
#    skip_builtin_functions: true

monolog:
    channels:
        - "access"
        - "modification"
        - "login"
        - "release"
        - "email"
        - "error"
        - "hook"
        
    handlers:
        accesshandler:
            type:           stream
            path:           %hexaa_log_dir%/access.log
            action_level:   info
            channels:       [security, access]
        audithandler:
            type:           stream
            path:           %hexaa_log_dir%/audit.log
            action_level:   info
            channels:       modification
        authhandler:
            type:           stream
            path:           %hexaa_log_dir%/auth.log
            action_level:   info
            channels:       [security, login]
        releasehandler:
            type:           stream
            path:           %hexaa_log_dir%/release.log
            action_level:   info
            channels:       release
        emailhandler:
            type:           stream
            path:           %hexaa_log_dir%/email.log
            action_level:   info
            channels:       email
        hookhandler:
            type:           stream
            path:           %hexaa_log_dir%/hook.log
            action_level:   debug
            channels:       hook
        errorhandler:
            type:           stream
            path:           %hexaa_log_dir%/error.log
            action_level:   warning
            level:          warning
            channels:       [access, modification, login, release, email, error, hook]
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        firephp:
            type:  firephp
            level: info
        chromephp:
            type:  chromephp
            level: info

assetic:
    use_controller: true

swiftmailer:
#    delivery_address: me@example.com
#    disable_delivery: true
