imports:
    - { resource: config.yml }

# In production environment you should know that the parameters for URL generation
# always pass the requirements. Otherwise it would break your link (or even site with
# strict_requirements = true). So we can disable the requirements check completely for
# enhanced performance with strict_requirements = null.
framework:
    router:
        strict_requirements: null

monolog:
    channels:
        - "access"
        - "audit"
    handlers:
        accesshandler:
            type:           stream
            path:           %kernel.logs_dir%/access.log
            action_level:   info
            channels:       [security, access]
        audithandler:
            type:           stream
            path:           %kernel.logs_dir%/audit.log
            action_level:   info
            channels:       audit
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug