imports:
    - { resource: config.yml }

# In production environment you should know that the parameters for URL generation
# always pass the requirements. Otherwise it would break your link (or even site with
# strict_requirements = true). So we can disable the requirements check completely for
# enhanced performance with strict_requirements = null.
framework:
    router:
        strict_requirements: null

monolog:
    channels:
        - "access"
        - "modification"
        - "login"
        - "release"
        - "email"
        - "error"
        
    handlers:
        accesshandler:
            type:           stream
            path:           %hexaa_log_dir%/access.log
            action_level:   info
            channels:       [security, access]
        audithandler:
            type:           stream
            path:           %hexaa_log_dir%/audit.log
            action_level:   info
            channels:       modification
        authhandler:
            type:           stream
            path:           %hexaa_log_dir%/auth.log
            action_level:   info
            channels:       [security, login]
        releasehandler:
            type:           stream
            path:           %hexaa_log_dir%/release.log
            action_level:   info
            channels:       release
        emailhandler:
            type:           stream
            path:           %hexaa_log_dir%/email.log
            action_level:   info
            channels:       email
        errorhandler:
            type:           stream
            path:           %hexaa_log_dir%/error.log
            action_level:   warning
            level:          warning
            channels:       [access, modification, login, release, email, error]
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  %hexaa_log_dir%/hexaa.log
            level: debug