imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    channels:
        - "access"
        - "audit"
    handlers:
        access:
            type:   stream
            path:   %kernel.logs_dir%/access.log
            channels: [security, access]
        audit:
            type:   stream
            path:   %kernel.logs_dir%/audit.log
            channels: audit
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        firephp:
            type:  firephp
            level: info
        chromephp:
            type:  chromephp
            level: info

assetic:
    use_controller: true

swiftmailer:
#    delivery_address: me@example.com
#    disable_delivery: true
