parameters:
    # Insert service entityids here.
    hexaa_service_entityids:
        https://example.com/ssp: 
            tech@doma.in: technical
            admin@doma.in: administrator
            support@doma.in: support