parameters:
    # Insert service entityids here.
    hexaa_service_entityids:
        https://example.com/ssp: 
            - type: technical
              email: tech@doma.in
              givenName: Techie Team
            - type: administration
              email: admin@doma.in
              givenName: Admin Team
            - type: support
              email: support@doma.in
              givenName: Support Team