parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     hexaa
    database_user:     someuser
    database_password: somepass

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt

    # Insert service entityids here.
    hexaa_service_entityids:
      - https://sp.example.org/shibboleth
      
    # Array of hexaa superadmins (fedid)
    hexaa_admins:
      - solazs@sztaki.hu
      
    # Master secret
    hexaa_master_secret: InsertSomeSecretHere
    
    # GetToken valid IPs:
    hexaa_get_token_ips:
      - localhost
    