parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     hexaa
    database_user:     someuser
    database_password: somepass

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    # you can generate a secret using:
    # tr -c -d '0123456789abcdefghijklmnopqrstuvwxyz' </dev/urandom | dd bs=32 count=1 2>/dev/null;echo
    secret:            ThisTokenIsNotSoSecretChangeIt
    
    # HEXAA UI URL
    hexaa_ui_url: https://path.to/hexaaui
    
    # HEXAA log directory
    # note: don't write / at the end!
    hexaa_log_dir: /var/log/hexaa
      
    # Master secret
    hexaa_master_secret: InsertSomeSecretHere
    
    # Set to false to disable consent check upon attribute release
    hexaa_consent_module: true
    
    # GetToken valid IPs:
    hexaa_get_token_ips:
      - localhost
    