security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_API:         ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]


    providers:
        saml:
            id: saml.service.user.provider
        ssp_api:
            id: ssp_apikey_user_provider
        personal_api:
            id: personal_apikey_user_provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        apikey_secured:
            pattern: ^/api/attributes[^pec]
            stateless: true
            provider: ssp_api
            simple-preauth:
                provider: ssp_api
                authenticator: ssp_apikey_authenticator
                
        restapi:
            pattern: ^/api/
            stateless: true
            provider: personal_api
            simple-preauth:
                provider: personal_api
                authenticator: personal_apikey_authenticator
            
            
        saml_secured:
            pattern: ^/.+
            saml: true
            access_denied_url: /unauthorized
            
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/css/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/, role: ROLE_API }
