FROM php:5.6-cli

RUN apt-get update && apt-get install -y \
    git unzip libmcrypt-dev libicu-dev \
    && docker-php-ext-install -j$(nproc) intl mcrypt pdo pdo_mysql mysqli bcmath

RUN apt-get install -y \
    libmemcached-dev zlib1g-dev \
    && pecl install memcached-2.2.0 \
    && docker-php-ext-enable memcached

RUN echo memory_limit = -1 > $PHP_INI_DIR/conf.d/memory_limit.ini
RUN echo max_execution_time = 300 > $PHP_INI_DIR/conf.d/max_execution_time.ini

WORKDIR /usr/bin
RUN ln -s /usr/local/bin/php php

ADD docker/run_hexaa_dev.sh /run_hexaa_dev.sh

RUN mkdir -p /usr/src/myapp
WORKDIR /usr/src/myapp

COPY . /usr/src/myapp

# This is a workaround for https://github.com/doctrine/DoctrineBundle/issues/351
# Should be removed ASAP.
ADD docker/parameters.yml /usr/src/myapp/app/config/parameters.yml

RUN curl https://getcomposer.org/installer -O
RUN php installer

RUN php composer.phar install

ADD docker/hexaa_admins.yml app/config/hexaa_admins.yml
ADD docker/hexaa_entityids.yml app/config/hexaa_entityids.yml

RUN rm -rf app/cache/*

WORKDIR /usr/src/myapp/web
CMD [ "/run_hexaa_dev.sh" ]
