FROM php:5.6-cli
COPY . /usr/src/myapp
ADD run_dev.sh /run_dev.sh
WORKDIR /usr/src/myapp

RUN curl https://getcomposer.org/installer -O
RUN php installer

RUN apt-get update && apt-get install -y \
    git unzip libmcrypt-dev libicu-dev \
    && docker-php-ext-install -j$(nproc) intl mcrypt pdo pdo_mysql mysqli bcmath

RUN apt-get install -y \
    libmemcached-dev zlib1g-dev \
    && pecl install memcached-2.2.0 \
    && docker-php-ext-enable memcached

RUN echo memory_limit = -1 > $PHP_INI_DIR/conf.d/memory_limit.ini

RUN php composer.phar install

ADD docker/hexaa_admins.yml app/config/hexaa_admins.yml

CMD [ "/run_dev.sh" ]
