services:
    security.authentication.factory.saml:
        class:  Hexaa\FOSSamlBundle\DependencyInjection\Security\Factory\SamlFactory
        tags:
            - { name: security.listener.factory }
