ssp:
    type:     rest
    resource: "Hexaa\ApiBundle\Controller\SspController"

service:
    type:     rest
    resource: "Hexaa\ApiBundle\Controller\ServiceController"
    
organization:
    type:     rest
    resource: "Hexaa\ApiBundle\Controller\OrganizationController"
    
entitlementpack:
    type:     rest
    resource: "Hexaa\ApiBundle\Controller\EntitlementpackController"
        
entitlement:
    type:     rest
    resource: "Hexaa\ApiBundle\Controller\EntitlementController"
 
role:
    type:     rest
    resource: "Hexaa\ApiBundle\Controller\RoleController"
    
principal:
    type:     rest
    resource: "Hexaa\ApiBundle\Controller\\PrincipalController"
    
servicechild:
    type:     rest
    parent:   service
    resource: "Hexaa\ApiBundle\Controller\ServiceChildController"
    
organizationchild:
    type:     rest
    parent:   organization
    resource: "Hexaa\ApiBundle\Controller\OrganizationChildController"
    
entitlementpackentitlement:
    type:     rest
    parent:   entitlementpack
    resource: "Hexaa\ApiBundle\Controller\EntitlementpackEntitlementController"
    
other:
    type:     rest
    resource: "Hexaa\ApiBundle\Controller\RestController"
