parameters:
    personal_apikey_user_provider.class: Hexaa\ApiBundle\Security\personalApiKey\PersonalApiKeyUserProvider
    personal_apikey_authenticator.class: Hexaa\ApiBundle\Security\personalApiKey\PersonalApiKeyAuthenticator
services:
    personal_apikey_user_provider:
        class: %personal_apikey_user_provider.class%
        arguments: [@service_container, "@monolog.logger.login", "@monolog.logger.modification"]
    personal_apikey_authenticator:
        class:     %personal_apikey_authenticator.class%
        arguments: ["@personal_apikey_user_provider", "@security.http_utils", "@monolog.logger.login"]
    validator.uniquie.valid_entityid:
        class: Hexaa\ApiBundle\Validator\Constraints\ValidEntityidValidator
        tags:
            - { name: validator.constraint_validator, alias: validentityid }
        arguments: [%hexaa_service_entityids%]
    validator.uniquie.invitation_has_valid_target:
        class: Hexaa\ApiBundle\Validator\Constraints\InvitationHasValidTargetValidator
        tags:
            - { name: validator.constraint_validator, alias: invitation_has_valid_target }
        arguments: [ @doctrine.orm.entity_manager, @security.context, %hexaa_admins% ]