imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

#jns_xhprof:
#    location_web:    http://localhost/xhprof
#    enabled:         true
#    skip_builtin_functions: true

monolog:
    channels:
        - "access"
        - "modification"
        - "login"
        - "release"
        - "email"
        - "error"
        - "hook"

    handlers:
        main:
            type:  stream
            path:  "php://stdout"
            level: debug

assetic:
    use_controller: true

swiftmailer:
#    delivery_address: me@example.com
#    disable_delivery: true
